pub const OPENWA_RELEASE_TAG: &str = env!("WA_STUDIO_OPENWA_RELEASE_TAG");
pub const OPENWA_CONTRACT_SHA256: &str = env!("WA_STUDIO_OPENWA_CONTRACT_SHA256");
pub const OPENWA_CONNECTOR_PLUGIN_ID: &str = "wa-studio-connector";
pub const OPENWA_CONNECTOR_PLUGIN_VERSION: &str = env!("WA_STUDIO_CONNECTOR_PLUGIN_VERSION");
pub const OPENWA_CONNECTOR_PLUGIN_URL: Option<&str> = option_env!("WA_STUDIO_CONNECTOR_PLUGIN_URL");
