import { HttpException, HttpStatus } from '@nestjs/common';
import type { RuntimeErrorDto } from '../../contracts/common/runtime-error.dto';

export type CampaignErrorCode =
  | 'CAMPAIGN_NOT_FOUND'
  | 'CAMPAIGN_SESSION_NOT_FOUND'
  | 'CAMPAIGN_NOT_EDITABLE'
  | 'CAMPAIGN_REVISION_CONFLICT'
  | 'CAMPAIGN_TARGETS_REVISION_CONFLICT'
  | 'CAMPAIGN_REVISION_INVALID'
  | 'CAMPAIGN_TARGETS_REVISION_INVALID'
  | 'CAMPAIGN_SCHEDULE_REQUIRED'
  | 'CAMPAIGN_SCHEDULE_INVALID'
  | 'CAMPAIGN_SCHEDULE_IN_PAST'
  | 'CAMPAIGN_TARGET_LIMIT_EXCEEDED'
  | 'CAMPAIGN_TARGET_DUPLICATE'
  | 'CAMPAIGN_TARGET_SESSION_MISMATCH'
  | 'CAMPAIGN_TARGET_NOT_FOUND'
  | 'CAMPAIGN_TARGET_SOURCE_NOT_FOUND'
  | 'CAMPAIGN_TARGET_SOURCE_SESSION_MISMATCH'
  | 'CAMPAIGN_TARGET_SOURCE_REVISION_CONFLICT'
  | 'CAMPAIGN_IDEMPOTENCY_KEY_REQUIRED'
  | 'CAMPAIGN_IDEMPOTENCY_KEY_INVALID'
  | 'CAMPAIGN_IDEMPOTENCY_CONFLICT'
  | 'CAMPAIGN_IDEMPOTENCY_KEY_RETIRED'
  | 'CAMPAIGN_DELETE_STATE_CONFLICT'
  | 'CAMPAIGN_DELETE_RUN_CONFLICT'
  | 'CAMPAIGN_RUN_IDEMPOTENCY_KEY_REQUIRED'
  | 'CAMPAIGN_RUN_IDEMPOTENCY_KEY_INVALID'
  | 'CAMPAIGN_RUN_IDEMPOTENCY_CONFLICT'
  | 'CAMPAIGN_RUN_LAUNCH_CONFLICT'
  | 'CAMPAIGN_RUN_REVISION_REQUIRED'
  | 'CAMPAIGN_RUN_REVISION_CONFLICT'
  | 'CAMPAIGN_RUN_PREFLIGHT_REQUIRED'
  | 'CAMPAIGN_RUN_PREFLIGHT_INVALID'
  | 'CAMPAIGN_RUN_SCHEDULE_EXPIRED'
  | 'CAMPAIGN_RUN_NOT_FOUND'
  | 'CAMPAIGN_RUN_STATE_CONFLICT'
  | 'CAMPAIGN_FILTER_STATUS_INVALID'
  | 'CAMPAIGN_FILTER_SCHEDULE_TYPE_INVALID'
  | 'CAMPAIGN_QUERY_INVALID';

export class CampaignError extends HttpException {
  constructor(
    status: HttpStatus,
    code: CampaignErrorCode,
    message: string,
    details?: Record<string, unknown>,
  ) {
    const body: RuntimeErrorDto = { code, message, ...(details ? { details } : {}) };
    super(body, status);
  }
}
