modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      follow_redirects: false

  wa_studio_discovery:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      follow_redirects: false
      fail_if_body_not_matches_regexp:
        - '"protocolVersion":2'
        - '"eventInboxUrl":"https://wa-events.onio.cc"'
