/* Generated by tooling/openwa-server-release.mjs. Do not edit by hand. */

export const OPENWA_RELEASE_TAG = '0.23.3' as const;
export const OPENWA_CONTRACT_SHA256 = '672e41d92423c99d3571c04ee54467ba45b3f707cfab3e698e5a9a053b128ea8' as const;
